### PR TITLE
Upvotes

### PR DESCRIPTION
**Pull request by eripheebs**

### CODE REVIEW

**Comment by paulalexrees** [comment]
:shipit: 💯 🎅

**Comment by kevinpmcc** [comment]
the upvotes look great and work well.

one issue we have is that in order to add a definition you should be logged in but on the terms detail page you have the add definition box even if you are not logged in. this results in error if you try to submit when not logged in.

we need to encase the form on the show.html.erb so it only shows if user is signed in I think. 
1. Does that sound like right solution?
2. Should we do it on this branch or another issue?

**Comment by kevinpmcc** [comment]
cool, after offline discussion merge this one then fix issue.

**Comment by kevinpmcc** [comment]
:shipit:

**Pull request merged**
